# Generated by Django 3.1.6 on 2021-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('deskrisaun', models.TextField()),
                ('kompleta', models.BooleanField(default=False)),
                ('data_kria', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
